bankpay/urls.py
from django.urls import path
from .views import pay_with_bank,index

from . import views

urlpatterns = [
    path('pay_with_bank/', pay_with_bank, name='pay_with_bank'),
    path('bankpay/', index, name="bankpay"),
    
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('posts/', views.post_list, name='blog'),
    path('posts/<slug:slug>/', views.post_detail, name='post_detail'),
]

msigana_ecommerce/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from msigana_ecommerce.admin_site import admin_site
from django.views.generic import TemplateView
from django.contrib.staticfiles.views import serve

# from django.contrib import admin

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', views.home, name='home'),
    path('services/', include('catering.urls')),
    path('store/', include('store.urls')),
    path('orders/', views.lookbook, name='lookbook'),
    path('blog/', include('blog.urls')),
    path('about-us/', views.about_us, name='about-us'),
    path('contact-us/', include('contact.urls')),
    path('accounts/', include('allauth.urls')),
    path('minerals/', views.minerals, name='minerals'),
    path('carts/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('bankpay/', include('bankpay.urls')),
    path('rewardpay', include('rewardpay.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

bankpay/models.py
from django.db import models
from users.models import CustomUser
import time
import random
import string
from django.utils.text import slugify
from django.utils.html import strip_tags
import html
from django.core.files.base import ContentFile
from PIL import Image
from io import BytesIO
from django.utils.text import slugify
import uuid


class Bankname(models.Model):
    name = models.CharField(max_length=200)
    account = models.CharField(max_length=250)
    slug = models.SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)

        super().save(*args, **kwargs)
    
class Paywithbank(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=11, decimal_places=2)
    payment_date = models.DateTimeField(auto_now_add=True)
    out_trade_no = models.CharField(max_length=60, editable=False)
    transaction_no = models.CharField(max_length=100, blank=False)
    payment_status = models.BooleanField(default=False)
    screenshot = models.ImageField(upload_to='images/bank', blank=False)
    bank_name = models.CharField(max_length=200)
    ref_number = models.CharField(max_length=200, unique=True)
    user_bank_account_name = models.CharField(max_length=200)
    paid_by_bank = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=13, blank=False)


    def save(self, *args, **kwargs):
        if not self.transaction_no:
            self.transaction_no = str(int(time.time() * 1000)) + ''.join(random.choices(string.ascii_letters + string.digits, k=3))

        try:
                # Check if the object already exists in the database
            this = Paywithbank.objects.get(id=self.id)
            if this.screenshot != self.screenshot:
                this.screenshot.delete(save=False)
        except Paywithbank.DoesNotExist:
            pass  # When it's a new object, do nothing
        
                # Optimize image before saving
        if self.screenshot:
            img = Image.open(self.screenshot)
            output = BytesIO()

            # Save the image in its original format
            img_format = img.format
            img.save(output, format=img_format, quality=75)
            output.seek(0)

            # Define a proper upload path for the image
            upload_path = 'images/bank/{}.{}'.format(uuid.uuid4(), img_format.lower())
            self.screenshot = ContentFile(output.read(), upload_path)

        super().save(*args, **kwargs)


    def delete(self, *args, **kwargs):
        self.screenshot.delete(save=False)
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.transaction_no
    

bankpay/forms.py
from django import forms

class BankpayForm(forms.Form):
    bank_name = forms.CharField(max_length=20, required=True)
    phone_number = forms.CharField(max_length=13, required=True)
    ref_number = forms.CharField(max_length=20, required=True)
    user_bank_account_name = forms.CharField(max_length=30, required=True)
    screenshot = forms.ImageField(required=False)

bankpay/views.py
from django.shortcuts import render
from django.http import JsonResponse
from users.models import CustomUser
from orders.models import Order
from .models import Paywithbank, Bankname
from django.urls import reverse
from decimal import Decimal
from .forms import BankpayForm
from users.models import CustomUser
from rewardpay.models import RewardRate

# Create your views here.
def index(request):
    banks = Bankname.objects.all()  # Retrieve all Bankname objects
    return render(request, 'bankpay.html', {'banks': banks})



def pay_with_bank(request):
    if request.method == 'POST':
        print("POST request received")
        user = CustomUser.objects.get(username=request.user.username)
        order = Order.objects.filter(user=request.user, payment_status=False).latest('order_date')
        total_amount = Decimal(order.order_total_prices)

        form = BankpayForm(request.POST, request.FILES)
        if form.is_valid():
            print("Bank Account Name:", form.cleaned_data['user_bank_account_name'])
            print("Screenshot:", form.cleaned_data['screenshot'])
            print("phone number", form.cleaned_data['phone_number'])
            print("ref number", form.cleaned_data['ref_number'])
            payment = Paywithbank(
                bank_name=form.cleaned_data['bank_name'],
                phone_number=form.cleaned_data['phone_number'],
                ref_number=form.cleaned_data['ref_number'],
                user_bank_account_name=form.cleaned_data['user_bank_account_name'],
                screenshot=form.cleaned_data['screenshot'],
                user=user,
                total_amount=total_amount,
                out_trade_no=order.outTradeNo,
            )
            payment.save()
            order.transaction_no = payment.transaction_no
            order.order_phone = payment.phone_number
            order.bank_ref_number = payment.ref_number
            order.save()
            user.phone_number = payment.phone_number
            user.save()

            return JsonResponse({'success': True, 'redirect_url':  reverse('order_complete')})  # Update with your success URL
        else:
            return JsonResponse({'success': False, 'message': 'Please fill in all the required information in the form.'})

    return JsonResponse({'success': False, 'message': 'Invalid request.'})

bankpay/templates/bankpay.html
{% extends 'base.html'%}
{% load static %}
{% block title%} Pay with a local Ethiopian bank account at Tanabeles Ecommerce in Addis Ababa, Ethiopia.
{% endblock %}
{% block content %}
    <!-- checkout form -->
    <div class="container mx-auto pt-4 pb-6 px-4 sm:px-8 md:px-16 lg:px-16 xl:px-48 2xl-px-64 2xl:max-w-full 3xl:w-2/3 md:mt-24">
       <div class="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
        <form id="payment-with-bank" method="POST" action="{% url 'pay_with_bank' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <h3 class="text-lg font-medium capitalize mb-4">
                Pay with Bank Account
            </h3>
            <div class="space-y-4">
                <div>
                    <label for="bank-name" class="block text-sm font-medium text-gray-700">Bank Name</label>
                    <select id="bank-name" name="bank_name" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                        <option value="">Select Bank</option> <!-- Add this line -->
                        {% for bank in banks %}
                            <option value="{{ bank.name }}">{{ bank.name }}</option>
                        {% endfor %}
                    </select>
                    
                </div>
                <div>
                    <label for="id_phone_number" class="block text-sm font-medium text-gray-700">Phone Number</label>
                    <input id="id_phone_number" type="text" name="phone_number" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" value="{{ request.user.phone_number|default:'' }}">
                </div>
                <div>
                    <label for="ref-number" class="block text-sm font-medium text-gray-700">Ref Number</label>
                    <input id="ref-number" type="text" name="ref_number" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                </div>
                <div>
                    <label for="user-bank-account-name" class="block text-sm font-medium text-gray-700">Bank Account Name</label>
                    <input id="user-bank-account-name" type="text" name="user_bank_account_name" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" value="{{ request.user.address|default:'' }}">
                </div>
                <div>
                    <label for="screenshot" class="block text-sm font-medium text-gray-700">Screenshot <span class="text-red-500">*</span></label>
                    <input id="screenshot" type="file" name="screenshot" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" required>
                    <!-- Add a <span> element with a red asterisk to indicate that the field is mandatory -->
                </div>
                <button id="submit-payment" type="button" class="bg-blue-500 border border-primary text-white px-4 py-3 font-medium rounded-md uppercase hover:bg-blue-800 hover:text-primary transition text-sm w-full block text-center">Submit Payment</button>
            </div>
        </form>
        <div class="mb-8">
            <h3 class="text-lg font-medium capitalize mb-4">Bank Accounts</h3>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                {% for bank in banks %}
                <div class="bg-white rounded-md p-4 shadow-md">
                    <h4 class="text-lg font-medium mb-2">Bank Name:  {{bank.name}}</h4>
                    <p class="text-gray-700">Account Number: {{bank.account}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
        <script>
            $(document).ready(function() {
                $('#submit-payment').click(function(event) {
                    // Prevent the default form submission
                    event.preventDefault();
        
                    // Create a FormData object to store form data
                    var formData = new FormData($('#payment-with-bank')[0]);
        
                    // Send an AJAX POST request to your backend server
                    $.ajax({
                        type: 'POST',
                        url: '{% url 'pay_with_bank' %}',
                        data: formData,
                        processData: false,
                        contentType: false,
                        success: function(response) {
                            if (response.success) {
                                // Redirect the user to a success page
                                window.location.href = response.redirect_url;
                            } else {
                                // Show an error message
                                alert(response.message);
                            }
                        },
                        error: function(xhr, errmsg, err) {
                            // Handle any errors
                            console.log('Error occurred:', errmsg);
                        }
                    });
                });
            });
        </script>
        
        
    </div>
    <!-- checkout form end -->
{% endblock %}